# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu
    timeout_min: 1000
    max_num_timeout: 5

trainer:
  hardware:
    seed: 0
    float16: true
    device: "cuda:0"
    world_size: 1
  logger:
    checkpoint_frequency: 10